// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1luO7Ke0oDIGD8q2-23nQ7qgM1QiDIqo',
    appId: '1:669556759134:web:dd8e500285c8e85a9332cf',
    messagingSenderId: '669556759134',
    projectId: 'chatapp2-584ed',
    authDomain: 'chatapp2-584ed.firebaseapp.com',
    storageBucket: 'chatapp2-584ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3QUKypDA_oqKCzDUqjj7B0ZB3t2DhIaM',
    appId: '1:669556759134:android:0c1f9217cc06d7ca9332cf',
    messagingSenderId: '669556759134',
    projectId: 'chatapp2-584ed',
    storageBucket: 'chatapp2-584ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1oAdOW3UdMFjOrGw007cEHwqkkJekXfc',
    appId: '1:669556759134:ios:cb4b29aef0bec5479332cf',
    messagingSenderId: '669556759134',
    projectId: 'chatapp2-584ed',
    storageBucket: 'chatapp2-584ed.appspot.com',
    iosBundleId: 'com.example.chatappmod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1oAdOW3UdMFjOrGw007cEHwqkkJekXfc',
    appId: '1:669556759134:ios:b7f2ae8f8ca4d6c39332cf',
    messagingSenderId: '669556759134',
    projectId: 'chatapp2-584ed',
    storageBucket: 'chatapp2-584ed.appspot.com',
    iosBundleId: 'com.example.chatappmod.RunnerTests',
  );
}
